name = "LLMAccess"
uuid = "1a9614b5-a00e-4537-a79a-85f37aa414d6"
authors = ["Xing Shi Cai <newptcai@tutanota.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
